spring.application.name=RootWPSP

# Nombre de la aplicaci\u00f3n
spring.application.name=RootWPSP

# Configuraci\u00f3n de MongoDB (Localhost)
# "iot_database" es el nombre que se crear\u00e1 autom\u00e1ticamente en tu MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/iot_RootWatch

# Puerto del servidor (por defecto es 8080)
server.port=8080

# Mostrar las consultas en la consola (\u00fatil para depurar en clase)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Configuraci\u00f3n de Jackson (para que las fechas se vean bonitas en el JSON)
spring.jackson.serialization.write-dates-as-timestamps=false


# ID de Cliente de Google Cloud (El de tipo "Aplicaci\u00f3n Web")
google.client.id=124048294753-bbr124v2d3uk222s1d4c49lc91q4erqm.apps.googleusercontent.com

# Seguridad de la API
rootwatch.api.key=CLAVE_SUPER_SECRETA
rootwatch.api.header=x-api-key
